tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "spring-io/tap"
brew "cask"
brew "gh"
brew "lua"
brew "highlight"
brew "jenv"
brew "maven"
brew "neovim", args: ["HEAD"]
brew "node"
brew "tree"
brew "spring-io/tap/spring-boot"
cask "font-hack-nerd-font"
cask "iterm2"
